# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/raphael/Documents/Perlin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/raphael/Documents/Perlin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raphael/Documents/Perlin/CMakeFiles /home/raphael/Documents/Perlin/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raphael/Documents/Perlin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Perlin

# Build rule for target.
Perlin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Perlin
.PHONY : Perlin

# fast build rule for target.
Perlin/fast:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/build
.PHONY : Perlin/fast

chunk.o: chunk.cpp.o

.PHONY : chunk.o

# target to build an object file
chunk.cpp.o:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/chunk.cpp.o
.PHONY : chunk.cpp.o

chunk.i: chunk.cpp.i

.PHONY : chunk.i

# target to preprocess a source file
chunk.cpp.i:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/chunk.cpp.i
.PHONY : chunk.cpp.i

chunk.s: chunk.cpp.s

.PHONY : chunk.s

# target to generate assembly for a file
chunk.cpp.s:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/chunk.cpp.s
.PHONY : chunk.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/main.cpp.s
.PHONY : main.cpp.s

module.o: module.cpp.o

.PHONY : module.o

# target to build an object file
module.cpp.o:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/module.cpp.o
.PHONY : module.cpp.o

module.i: module.cpp.i

.PHONY : module.i

# target to preprocess a source file
module.cpp.i:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/module.cpp.i
.PHONY : module.cpp.i

module.s: module.cpp.s

.PHONY : module.s

# target to generate assembly for a file
module.cpp.s:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/module.cpp.s
.PHONY : module.cpp.s

modules/world.o: modules/world.cpp.o

.PHONY : modules/world.o

# target to build an object file
modules/world.cpp.o:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/modules/world.cpp.o
.PHONY : modules/world.cpp.o

modules/world.i: modules/world.cpp.i

.PHONY : modules/world.i

# target to preprocess a source file
modules/world.cpp.i:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/modules/world.cpp.i
.PHONY : modules/world.cpp.i

modules/world.s: modules/world.cpp.s

.PHONY : modules/world.s

# target to generate assembly for a file
modules/world.cpp.s:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/modules/world.cpp.s
.PHONY : modules/world.cpp.s

noise2d.o: noise2d.cpp.o

.PHONY : noise2d.o

# target to build an object file
noise2d.cpp.o:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/noise2d.cpp.o
.PHONY : noise2d.cpp.o

noise2d.i: noise2d.cpp.i

.PHONY : noise2d.i

# target to preprocess a source file
noise2d.cpp.i:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/noise2d.cpp.i
.PHONY : noise2d.cpp.i

noise2d.s: noise2d.cpp.s

.PHONY : noise2d.s

# target to generate assembly for a file
noise2d.cpp.s:
	$(MAKE) -f CMakeFiles/Perlin.dir/build.make CMakeFiles/Perlin.dir/noise2d.cpp.s
.PHONY : noise2d.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Perlin"
	@echo "... edit_cache"
	@echo "... chunk.o"
	@echo "... chunk.i"
	@echo "... chunk.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... module.o"
	@echo "... module.i"
	@echo "... module.s"
	@echo "... modules/world.o"
	@echo "... modules/world.i"
	@echo "... modules/world.s"
	@echo "... noise2d.o"
	@echo "... noise2d.i"
	@echo "... noise2d.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

